location /org/ {
	internal;
	alias /var/www/cleberg.net/org/;
	default_type text/plain;
	add_header Content-Type "text/plain; charset=utf-8";
}

location / {
	try_files $uri $uri/ =404;
}

location /blog/ {
	rewrite ^/blog/((?!index)[^/]+)/(.*)$ /blog/$1.html permanent;
	if ($http_accept ~* "text/markdown") {
		rewrite ^/blog/([^/]+)\.html$ /org/blog/$1.org last;
	}
}

location ~ ^/([^/]+)\.html$ {
	if ($http_accept ~* "text/markdown") {
		rewrite ^/([^/]+)\.html$ /org/$1.org last;
	}
	try_files $uri =404;
}

location /atom.xml { return 301 $scheme://$host/feed.xml; }
location /blog/salary-transparency.html { return 301 $scheme://$host/salary/; }
