# ----------------------------------------------------------------------
# | Certificate files — cleberg.net                                    |
# ----------------------------------------------------------------------

# This default SSL certificate will be served whenever the client lacks support
# for SNI (Server Name Indication).
#
# (1) Certificate and key files location
#     https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_certificate
#
# (2) Intermediate certificate for OCSP stapling
#     https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_trusted_certificate

ssl_certificate         /etc/letsencrypt/live/cleberg.net/fullchain.pem;
ssl_certificate_key     /etc/letsencrypt/live/cleberg.net/privkey.pem;
ssl_trusted_certificate /etc/letsencrypt/live/cleberg.net/chain.pem;
