ssl_certificate         /etc/letsencrypt/live/reminiscecleberg.com/fullchain.pem;
ssl_certificate_key     /etc/letsencrypt/live/reminiscecleberg.com/privkey.pem;
ssl_trusted_certificate /etc/letsencrypt/live/reminiscecleberg.com/chain.pem;
