server {
    listen 443;
    http2 on;
    server_name 1kb.zerolabs.sh;

    root /var/www/1kb;
    index index.html;

    server_tokens off;
    etag off;
    if_modified_since off;
    expires off;
    gzip off;
    gzip_vary off;
    charset off;

    location = / {
        try_files /index.html =404;
    }

    location = /index.html {
        try_files /index.html =404;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name 1kb.zerolabs.sh;
    return 301 https://1kb.zerolabs.sh$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name 1kb.cleberg.net;
    return 301 https://1kb.zerolabs.sh$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name 1kb.cleberg.net;

    include custom.d/tls/ssl_engine.conf;
    include custom.d/tls/certificate_files.conf;
    include custom.d/tls/policy_strict.conf;

    return 301 https://1kb.zerolabs.sh$request_uri;
}
