server {
	listen [::]:443 ssl;
	listen 443 ssl;
	http2 on;
	server_name ao.zerolabs.sh;
	add_header Onion-Location "http://7lyqrn4ofxdq7lfporviu44zpc42wooh2bqazfhvpscgwby2vcwldzad.onion$request_uri" always;
	include custom.d/tls/ssl_engine.conf;
	include custom.d/tls/certificate_files.conf;
	include custom.d/tls/policy_strict.conf;
	include custom.d/basic.conf;
	location / {
		set $upstream http://127.0.0.1:9380;
		proxy_pass $upstream;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name ao.zerolabs.sh;
    return 301 https://ao.zerolabs.sh$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name ao.cleberg.net;
    return 301 https://ao.zerolabs.sh$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name ao.cleberg.net;

    include custom.d/tls/ssl_engine.conf;
    include custom.d/tls/certificate_files.conf;
    include custom.d/tls/policy_strict.conf;

    return 301 https://ao.zerolabs.sh$request_uri;
}
