server {
	listen 10002;
	server_name ao.zerolabs.sh ao.cleberg.net;

	if ($host = ao.cleberg.net) {
		return 301 https://ao.zerolabs.sh$request_uri;
	}

	add_header Onion-Location "http://7lyqrn4ofxdq7lfporviu44zpc42wooh2bqazfhvpscgwby2vcwldzad.onion$request_uri" always;
	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}


