server {
	listen 10003;
	server_name art.cleberg.net art.zerolabs.sh  mplqs2jxkjd5wxak3zjv55oxyadf4vwzx6ksgj4ztftndjl6elgsf4qd.onion;
	add_header Onion-Location "http://mplqs2jxkjd5wxak3zjv55oxyadf4vwzx6ksgj4ztftndjl6elgsf4qd.onion$request_uri" always;

	if ($host = art.cleberg.net) {
		return 301 https://art.zerolabs.sh$request_uri;
	}

	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}

