server {
	listen 443 ssl;
	http2 on;
	server_name art.cleberg.net art.zerolabs.sh  mplqs2jxkjd5wxak3zjv55oxyadf4vwzx6ksgj4ztftndjl6elgsf4qd.onion;
	add_header Onion-Location "http://mplqs2jxkjd5wxak3zjv55oxyadf4vwzx6ksgj4ztftndjl6elgsf4qd.onion$request_uri" always;

	if ($host = art.cleberg.net) {
		return 301 https://art.zerolabs.sh$request_uri;
	}

	include custom.d/tls/ssl_engine.conf;
	include custom.d/tls/certificate_files_cleberg_net.conf;
	include custom.d/tls/policy_strict.conf;
	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}

server {
    listen 80;
    server_name art.zerolabs.sh art.cleberg.net;
    return 301 https://art.zerolabs.sh$request_uri;
}
