server {
	listen 443 ssl;
	http2 on;
	server_name auth.zerolabs.sh;
	include custom.d/tls/ssl_engine.conf;
	include custom.d/tls/certificate_files_cleberg_net.conf;
	include custom.d/tls/policy_strict.conf;
	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/basic.conf;
	}
	location /api/verify { proxy_pass $backend_address; }
}

server {
    listen 80;
    server_name auth.zerolabs.sh;
    return 301 https://auth.zerolabs.sh$request_uri;
}
