server {
	listen 10004;
	server_name auth.zerolabs.sh auth.cleberg.net;

	if ($host = auth.cleberg.net) {
	    return 301 https://auth.zerolabs.sh$request_uri;
	}
	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/basic.conf;
	}
	location /api/verify { proxy_pass $backend_address; }
}

