server {
	listen 443 ssl;
	http2 on;
	server_name bb.zerolabs.sh;

	include custom.d/tls/ssl_engine.conf;
	include custom.d/tls/certificate_files_zerolabs_sh.conf;
	include custom.d/tls/policy_strict.conf;
	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/basic.conf;
		proxy_read_timeout 300s;
		proxy_send_timeout 300s;
		proxy_connect_timeout 300s;
	}
	include custom.d/security/robots_index_only.conf;
}

server {
    listen 80;
    server_name bb.zerolabs.sh;
    return 301 https://bb.zerolabs.sh$request_uri;
}
