server {
	listen 10005;
	server_name bb.zerolabs.sh bb.cleberg.net;

	if ($host = bb.cleberg.net) {
	    return 301 https://bb.zerolabs.sh$request_uri;
	}

	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/basic.conf;
		proxy_read_timeout 300s;
		proxy_send_timeout 300s;
		proxy_connect_timeout 300s;
	}
	include custom.d/security/robots_index_only.conf;
}

