server {
	listen 10006;
	server_name br.zerolabs.sh pkft6saqbmn6he5g626fphvlijmkdf4rzckjw6r57zsmuqm4ukd6i5ad.onion br.cleberg.net;

	if ($host = br.cleberg.net) {
	    return 301 https://br.zerolabs.sh$request_uri;
	}
	add_header Onion-Location "http://pkft6saqbmn6he5g626fphvlijmkdf4rzckjw6r57zsmuqm4ukd6i5ad.onion$request_uri" always;
	include custom.d/basic.conf;
    location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/basic.conf;
    }
    include custom.d/security/robots_index_only.conf;
}



