server {
    listen 10008;
    server_name bw.zerolabs.sh z7kc27ceokwgddrcspxx4eb7b6xqmtjj26nohg3wgt6hsnnlfmk4apqd.onion bw.cleberg.net;

    if ($host = bw.cleberg.net) {
        return 301 https://bw.zerolabs.sh$request_uri;
    }
	add_header Onion-Location "http://z7kc27ceokwgddrcspxx4eb7b6xqmtjj26nohg3wgt6hsnnlfmk4apqd.onion$request_uri" always;
    include custom.d/basic.conf;
    location / {
             proxy_pass $backend_address;
             include custom.d/reverse_proxy/basic.conf;
    }
    include custom.d/security/robots_index_only.conf;
}



