server {
	listen 10011;
	server_name cleberg.net;
    error_log /var/log/nginx/cleberg.net.error.log;
	include custom.d/basic.conf;
	include custom.d/security/strict-transport-security.conf;
	include custom.d/security/content-security-policy.conf;
	include custom.d/security/permissions-policy.conf;
	root /var/www/cleberg.net/;

	add_header Onion-Location "http://paske4urhs6nttrtlkuwa5cowum3fjkc6yv6kl4ncx3mjxcd77764nqd.onion$request_uri" always;

	include custom.d/sites/cleberg_net_static_locations.conf;
}

server {
    listen 10012;
    server_name hutch.cleberg.net;
    include custom.d/basic.conf;
    include custom.d/security/strict-transport-security.conf;
    include custom.d/security/content-security-policy.conf;
    include custom.d/security/permissions-policy.conf;

	location = /privacy.html {
		return 301 https://zerolabs.sh/hutch/privacy-policy/;
	}

	location = / {
		return 301 https://zerolabs.sh/hutch/;
	}
}

server {
    listen 10013;
    server_name paske4urhs6nttrtlkuwa5cowum3fjkc6yv6kl4ncx3mjxcd77764nqd.onion;
    include custom.d/basic.conf;
    root /var/www/cleberg.net/;

    include custom.d/sites/cleberg_net_static_locations.conf;
}
