server {
	listen [::]:443 ssl;
	listen 443 ssl;
	http2 on;
	server_name cv.cleberg.net;
	add_header Onion-Location "http://xe43aewwiybmbo5qsstx7t5kmgkd2ei4bkkvqinwd7fxfmkekvnjbbad.onion$request_uri" always;
	include custom.d/tls/ssl_engine.conf;
	include custom.d/tls/certificate_files.conf;
	include custom.d/tls/policy_strict.conf;
	include custom.d/basic.conf;
	root /var/www/cv/;
	autoindex on;
	location / { try_files $uri $uri/ /index.html; }
}

server {
    listen 127.0.0.1:8081;
    server_name xe43aewwiybmbo5qsstx7t5kmgkd2ei4bkkvqinwd7fxfmkekvnjbbad.onion;
    include custom.d/basic.conf;
    root /var/www/cv/;
    autoindex on;
    location / { try_files $uri $uri/ /index.html; }
}
