server {
	listen 10014;
	server_name cv.cleberg.net;
	add_header Onion-Location "http://xe43aewwiybmbo5qsstx7t5kmgkd2ei4bkkvqinwd7fxfmkekvnjbbad.onion$request_uri" always;
	include custom.d/basic.conf;
	root /var/www/cv/;
	autoindex on;
	location / { try_files $uri $uri/ /index.html; }
}

server {
    listen 10015;
    server_name xe43aewwiybmbo5qsstx7t5kmgkd2ei4bkkvqinwd7fxfmkekvnjbbad.onion;
    include custom.d/basic.conf;
    root /var/www/cv/;
    autoindex on;
    location / { try_files $uri $uri/ /index.html; }
}
