server {
	listen 10016;
	server_name ddns.zerolabs.sh ddns.cleberg.net;

	if ($host = ddns.cleberg.net) {
	    return 301 https://ddns.zerolabs.sh$request_uri;
	}
	include custom.d/basic.conf;
	location /authelia { include custom.d/reverse_proxy/authelia.conf; }
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/authelia_request.conf;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}

