server {
	listen 10017;
	server_name files.cleberg.net;
	add_header Onion-Location "http://yt2y635dc6zyxziy5ytkfz36bmkgcxuccq3meom6qp44gjdat54wt5id.onion$request_uri" always;
	include custom.d/basic.conf;
	root /var/www/files/;
	autoindex on;
	location / { try_files $uri $uri/ /index.html; }
}

server {
    listen 10018;
    server_name yt2y635dc6zyxziy5ytkfz36bmkgcxuccq3meom6qp44gjdat54wt5id.onion;
    include custom.d/basic.conf;
    root /var/www/files/;
    autoindex on;
    location / { try_files $uri $uri/ /index.html; }
}

