server {
	listen 10019;
	server_name gh.zerolabs.sh gh.cleberg.net;

	if ($host = gh.cleberg.net) {
	    return 301 https://gh.zerolabs.sh$request_uri;
	}
	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}



