server {
	listen 10022;
	server_name hat.zerolabs.sh jfrkztgin2ngoj2fnssc2m2j2ycpchmrhzhudaucgvaib5iqwgfxexyd.onion hat.cleberg.net;

	if ($host = hat.cleberg.net) {
	    return 301 https://hat.zerolabs.sh$request_uri;
	}
	add_header Onion-Location "http://jfrkztgin2ngoj2fnssc2m2j2ycpchmrhzhudaucgvaib5iqwgfxexyd.onion$request_uri" always;
	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/basic.conf;
	}
    include custom.d/security/robots_index_only.conf;
}



