server {
    listen 10023;
    listen 10024;
    server_name hn.zerolabs.sh r3yfeffyj7ornpikojmw75u3sn2la7tqnmcmwgv2ov7if24sm5czqeid.onion hn.cleberg.net;

    if ($host = hn.cleberg.net) {
        return 301 https://hn.zerolabs.sh$request_uri;
    }
    root /var/www/hn/output/;
    autoindex on;
    add_header Onion-Location "http://r3yfeffyj7ornpikojmw75u3sn2la7tqnmcmwgv2ov7if24sm5czqeid.onion$request_uri" always;
    include custom.d/basic.conf;
    location / { try_files $uri $uri/ /index.html; }
}



