server {
	listen 10025;
	server_name img.cleberg.net;
	add_header Onion-Location "http://ltf2dfg7tj263ll24lxuq7igejcrhcazjp6whgg6u6vyjir2iahqggad.onion$request_uri" always;
	include custom.d/basic.conf;
	root /var/www/img/;
	autoindex on;
	location / { try_files $uri $uri/ =404; }
}

server {
    listen 10026;
    server_name ltf2dfg7tj263ll24lxuq7igejcrhcazjp6whgg6u6vyjir2iahqggad.onion;
    include custom.d/basic.conf;
    root /var/www/img/;
    autoindex on;
    location / { try_files $uri $uri/ =404; }
}
