server {
	listen 10027;
	server_name irc.zerolabs.sh irc.cleberg.net;

	if ($host = irc.cleberg.net) {
	    return 301 https://irc.zerolabs.sh$request_uri;
	}
	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
	}
	include custom.d/security/robots_index_only.conf;
}

