server {
	listen [::]:443 ssl;
	listen 443 ssl;
	http2 on;
	server_name ld.zerolabs.sh  u3tyzuhs7o4hkizpbcxbm5yqzj74bjqb3phfqfszrx4u75dua7lpf7ad.onion;
	add_header Onion-Location "http://u3tyzuhs7o4hkizpbcxbm5yqzj74bjqb3phfqfszrx4u75dua7lpf7ad.onion$request_uri" always;
	include custom.d/tls/ssl_engine.conf;
	include custom.d/tls/certificate_files.conf;
	include custom.d/tls/policy_strict.conf;
	include custom.d/basic.conf;
	location / {
		set $upstream http://127.0.0.1:3004;
		proxy_pass $upstream;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name ld.zerolabs.sh;
    return 301 https://ld.zerolabs.sh$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name ld.cleberg.net;
    return 301 https://ld.zerolabs.sh$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name ld.cleberg.net;

    include custom.d/tls/ssl_engine.conf;
    include custom.d/tls/certificate_files.conf;
    include custom.d/tls/policy_strict.conf;

    return 301 https://ld.zerolabs.sh$request_uri;
}
