server {
	listen 10029;
	server_name lt.zerolabs.sh nxw6545qeepw2s2kngowsxbcizjcxyimn7dq2bpvr3sqabsu2juj6gyd.onion lt.cleberg.net;

	if ($host = lt.cleberg.net) {
	    return 301 https://lt.zerolabs.sh$request_uri;
	}
	add_header Onion-Location "http://nxw6545qeepw2s2kngowsxbcizjcxyimn7dq2bpvr3sqabsu2juj6gyd.onion$request_uri" always;
	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}



