server {
	listen 10030;
	server_name mz.zerolabs.sh ltawlmsk6vhrig2awwshnduiv45anelx3thepkd6xh4n2s4jxu7wyrid.onion mz.cleberg.net;

	if ($host = mz.cleberg.net) {
	    return 301 https://mz.zerolabs.sh$request_uri;
	}
	add_header Onion-Location "http://ltawlmsk6vhrig2awwshnduiv45anelx3thepkd6xh4n2s4jxu7wyrid.onion$request_uri" always;
	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}



