server {
	listen 127.0.0.1:10031;
	server_name office.zerolabs.sh;

	add_header Onion-Location "http://uwtjz6pof52bzdkj242mub77ls2ji3qiznbsuoir235rxynqxadpghid.onion$request_uri" always;
	root /var/www/office/;
	include custom.d/basic.conf;
	location / { try_files $uri $uri/ /index.html; }
}
server {
    listen 127.0.0.1:10032;
    server_name uwtjz6pof52bzdkj242mub77ls2ji3qiznbsuoir235rxynqxadpghid.onion;
    include custom.d/basic.conf;
    root /var/www/office/;
    location / { try_files $uri $uri/ /index.html; }
}



