server {
	listen 10031;
	server_name office.zerolabs.sh office.cleberg.net;

	if ($host = office.cleberg.net) {
	    return 301 https://office.zerolabs.sh$request_uri;
	}
	add_header Onion-Location "http://uwtjz6pof52bzdkj242mub77ls2ji3qiznbsuoir235rxynqxadpghid.onion$request_uri" always;
	root /var/www/office/;
	include custom.d/basic.conf;
	location / { try_files $uri $uri/ /index.html; }
}
server {
    listen 10032;
    server_name uwtjz6pof52bzdkj242mub77ls2ji3qiznbsuoir235rxynqxadpghid.onion;
    include custom.d/basic.conf;
    root /var/www/office/;
    location / { try_files $uri $uri/ /index.html; }
}



