server {
	listen 443 ssl;
	http2 on;
	server_name office.zerolabs.sh;
	add_header Onion-Location "http://uwtjz6pof52bzdkj242mub77ls2ji3qiznbsuoir235rxynqxadpghid.onion$request_uri" always;
	root /var/www/office/;
	include custom.d/tls/ssl_engine.conf;
	include custom.d/tls/certificate_files.conf;
	include custom.d/tls/policy_strict.conf;
	include custom.d/basic.conf;
	location / { try_files $uri $uri/ /index.html; }
}
server {
    listen 127.0.0.1:8088;
    server_name uwtjz6pof52bzdkj242mub77ls2ji3qiznbsuoir235rxynqxadpghid.onion;
    include custom.d/basic.conf;
    root /var/www/office/;
    location / { try_files $uri $uri/ /index.html; }
}

server {
    listen 80;
    server_name office.zerolabs.sh;
    return 301 https://office.zerolabs.sh$request_uri;
}

server {
    listen 80;
    server_name office.cleberg.net;
    return 301 https://office.zerolabs.sh$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name office.cleberg.net;

    include custom.d/tls/ssl_engine.conf;
    include custom.d/tls/certificate_files.conf;
    include custom.d/tls/policy_strict.conf;

    return 301 https://office.zerolabs.sh$request_uri;
}
