server {
	listen 127.0.0.1:10033;
	server_name org.zerolabs.sh;

	add_header Onion-Location "http://7vsifofpucgi3wva52nbwhwglrmbyxgdapbkkmgniqlsskspux5zocyd.onion$request_uri" always;
	root /var/www/org/;
	include custom.d/basic.conf;
	location / { try_files $uri $uri/ /index.html; }
}
server {
    listen 127.0.0.1:10034;
    server_name 7vsifofpucgi3wva52nbwhwglrmbyxgdapbkkmgniqlsskspux5zocyd.onion;
    include custom.d/basic.conf;
    root /var/www/org/;
    location / { try_files $uri $uri/ /index.html; }
}



