server {
	listen 10033;
	server_name org.zerolabs.sh org.cleberg.net;

	if ($host = org.cleberg.net) {
	    return 301 https://org.zerolabs.sh$request_uri;
	}
	add_header Onion-Location "http://7vsifofpucgi3wva52nbwhwglrmbyxgdapbkkmgniqlsskspux5zocyd.onion$request_uri" always;
	root /var/www/org/;
	include custom.d/basic.conf;
	location / { try_files $uri $uri/ /index.html; }
}
server {
    listen 10034;
    server_name 7vsifofpucgi3wva52nbwhwglrmbyxgdapbkkmgniqlsskspux5zocyd.onion;
    include custom.d/basic.conf;
    root /var/www/org/;
    location / { try_files $uri $uri/ /index.html; }
}



