server {
	listen [::]:443 ssl;
	listen 443 ssl;
	http2 on;
	server_name org.zerolabs.sh;
	add_header Onion-Location "http://7vsifofpucgi3wva52nbwhwglrmbyxgdapbkkmgniqlsskspux5zocyd.onion$request_uri" always;
	root /var/www/org/;
	include custom.d/tls/ssl_engine.conf;
	include custom.d/tls/certificate_files.conf;
	include custom.d/tls/policy_strict.conf;
	include custom.d/basic.conf;
	location / { try_files $uri $uri/ /index.html; }
}
server {
    listen 127.0.0.1:8085;
    server_name 7vsifofpucgi3wva52nbwhwglrmbyxgdapbkkmgniqlsskspux5zocyd.onion;
    include custom.d/basic.conf;
    root /var/www/org/;
    location / { try_files $uri $uri/ /index.html; }
}

server {
    listen 80;
    listen [::]:80;
    server_name org.cleberg.net;
    return 301 https://org.zerolabs.sh$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name org.cleberg.net;

    include custom.d/tls/ssl_engine.conf;
    include custom.d/tls/certificate_files.conf;
    include custom.d/tls/policy_strict.conf;

    return 301 https://org.zerolabs.sh$request_uri;
}
