server {
	listen 10035;
	server_name paste.zerolabs.sh ciserod7fbncypo762qcqtowldl3qjhlojfnmguiuvcj3rcyrhqs6ead.onion paste.cleberg.net;

	if ($host = paste.cleberg.net) {
	    return 301 https://paste.zerolabs.sh$request_uri;
	}
	add_header Onion-Location "http://ciserod7fbncypo762qcqtowldl3qjhlojfnmguiuvcj3rcyrhqs6ead.onion$request_uri" always;
	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}



