server {
	listen 10036;
	server_name pb.zerolabs.sh pb.cleberg.net;

	if ($host = pb.cleberg.net) {
	    return 301 https://pb.zerolabs.sh$request_uri;
	}

	error_log /var/log/nginx/pb.log;

	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}



