server {
	listen 10038;
	server_name pin.zerolabs.sh 3rtmxu6slammicquf5cpgiptjpzht3n342vh62utoyxchds5r76tadad.onion pin.cleberg.net;

	if ($host = pin.cleberg.net) {
	    return 301 https://pin.zerolabs.sh$request_uri;
	}
	add_header Onion-Location "http://3rtmxu6slammicquf5cpgiptjpzht3n342vh62utoyxchds5r76tadad.onion$request_uri" always;
	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}



