server {
	listen 443 ssl;
	http2 on;
	server_name pin.zerolabs.sh  3rtmxu6slammicquf5cpgiptjpzht3n342vh62utoyxchds5r76tadad.onion;
	add_header Onion-Location "http://3rtmxu6slammicquf5cpgiptjpzht3n342vh62utoyxchds5r76tadad.onion$request_uri" always;
	include custom.d/tls/ssl_engine.conf;
	include custom.d/tls/certificate_files_cleberg_net.conf;
	include custom.d/tls/policy_strict.conf;
	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}

server {
    listen 80;
    server_name pin.zerolabs.sh;
    return 301 https://pin.zerolabs.sh$request_uri;
}

server {
    listen 80;
    server_name pin.cleberg.net;
    return 301 https://pin.zerolabs.sh$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name pin.cleberg.net;

    include custom.d/tls/ssl_engine.conf;
    include custom.d/tls/certificate_files_cleberg_net.conf;
    include custom.d/tls/policy_strict.conf;

    return 301 https://pin.zerolabs.sh$request_uri;
}
