server {
	listen 10039;
	server_name piped.zerolabs.sh pipedapi.zerolabs.sh pipedproxy.zerolabs.sh 5ttqjwhhcxh7apxrge5b5cjqceiibrjlqv2hhtmukwfsitbzqk5hh4id.onion piped.cleberg.net;

	if ($host = piped.cleberg.net) {
	    return 301 https://piped.zerolabs.sh$request_uri;
	}
	add_header Onion-Location "http://5ttqjwhhcxh7apxrge5b5cjqceiibrjlqv2hhtmukwfsitbzqk5hh4id.onion$request_uri" always;
	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
		proxy_set_header Host $host;
	}
	include custom.d/security/robots_index_only.conf;
}



