server {
	listen 10040;
	server_name projects.zerolabs.sh projects.cleberg.net;

	if ($host = projects.cleberg.net) {
	    return 301 https://projects.zerolabs.sh$request_uri;
	}
	add_header Onion-Location "http://krednuajd2wpt67ozmkollddpbdphpeyh74hbenagzoxqjncrtrgxkid.onion$request_uri" always;
	root /var/www/projects/;
	autoindex on;
	include custom.d/basic.conf;
	location / { try_files $uri $uri/ /index.html; }
}

server {
    listen 10041;
    server_name krednuajd2wpt67ozmkollddpbdphpeyh74hbenagzoxqjncrtrgxkid.onion;
    include custom.d/basic.conf;
    root /var/www/projects/;
    autoindex on;
    location / { try_files $uri $uri/ /index.html; }
}



