server {
	listen 127.0.0.1:10040;
	server_name projects.zerolabs.sh;

	add_header Onion-Location "http://krednuajd2wpt67ozmkollddpbdphpeyh74hbenagzoxqjncrtrgxkid.onion$request_uri" always;
	root /var/www/projects/;
	autoindex on;
	include custom.d/basic.conf;
	location / { try_files $uri $uri/ /index.html; }
}

server {
    listen 127.0.0.1:10041;
    server_name krednuajd2wpt67ozmkollddpbdphpeyh74hbenagzoxqjncrtrgxkid.onion;
    include custom.d/basic.conf;
    root /var/www/projects/;
    autoindex on;
    location / { try_files $uri $uri/ /index.html; }
}



