server {
	listen 10042;
	server_name rd.zerolabs.sh voyxxivcoupelvedthpbjqsrdhkn4ty7qjurvsif4qbjejnldisqs5ad.onion rd.cleberg.net;

	if ($host = rd.cleberg.net) {
	    return 301 https://rd.zerolabs.sh$request_uri;
	}
	add_header Onion-Location "http://voyxxivcoupelvedthpbjqsrdhkn4ty7qjurvsif4qbjejnldisqs5ad.onion$request_uri" always;
	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}



