server {
	listen 443 ssl;
	http2 on;
	server_name www.reminiscecleberg.com;
	include custom.d/tls/ssl_engine.conf;
	include custom.d/tls/policy_strict.conf;
	include custom.d/tls/certificate_files_reminiscecleberg_com.conf;
	return 301 $scheme://reminiscecleberg.com$request_uri;
}


server {
	listen 443 ssl;
	http2 on;
	server_name reminiscecleberg.com;
	root /var/www/reminiscecleberg.com/;
	include custom.d/tls/ssl_engine.conf;
	include custom.d/tls/policy_strict.conf;
	include custom.d/tls/certificate_files_reminiscecleberg_com.conf;
	include custom.d/basic.conf;
	location / { try_files $uri $uri/ =404; }
}

server {
	listen 80;
	server_name www.reminiscecleberg.com reminiscecleberg.com;
	return 301 https://reminiscecleberg.com$request_uri;
}
