server {
	listen [::]:443 ssl;
	listen 443 ssl;
	http2 on;
	server_name rl.cleberg.net  s5wpjol4xe2mszhz4hoqobv4pqmoihb65dz2lbibujjjvhbpjvu45lad.onion;
	add_header Onion-Location "http://s5wpjol4xe2mszhz4hoqobv4pqmoihb65dz2lbibujjjvhbpjvu45lad.onion$request_uri" always;
	include custom.d/tls/ssl_engine.conf;
	include custom.d/tls/certificate_files.conf;
	include custom.d/tls/policy_strict.conf;
	include custom.d/basic.conf;
	location /authelia { include custom.d/reverse_proxy/authelia.conf; }
	location / {
		set $upstream http://192.168.0.251:8983;
		proxy_pass $upstream;
		include custom.d/reverse_proxy/authelia_request.conf;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}
