server {
	listen 10050;
	server_name ssh.zerolabs.sh ssh.cleberg.net;

	if ($host = ssh.cleberg.net) {
	    return 301 https://ssh.zerolabs.sh$request_uri;
	}
	include custom.d/basic.conf;
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}

