server {
	listen [::]:443 ssl;
	listen 443 ssl;
	http2 on;
	server_name wyl.cleberg.net  rdbegz4y6agv7izjowoicbqmslglnqwt7sk745yls4xm276jmayqtmid.onion;
	add_header Onion-Location "http://rdbegz4y6agv7izjowoicbqmslglnqwt7sk745yls4xm276jmayqtmid.onion$request_uri" always;
	include custom.d/tls/ssl_engine.conf;
	include custom.d/tls/certificate_files.conf;
	include custom.d/tls/policy_strict.conf;
	include custom.d/basic.conf;
	location /authelia { include custom.d/reverse_proxy/authelia.conf; }
	location / {
		set $upstream http://192.168.0.251:8840;
		proxy_pass $upstream;
		include custom.d/reverse_proxy/authelia_request.conf;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}
