server {
	listen 443 ssl;
	http2 on;
	server_name zb.zerolabs.sh;
	include custom.d/tls/ssl_engine.conf;
	include custom.d/tls/certificate_files_cleberg_net.conf;
	include custom.d/tls/policy_strict.conf;
	include custom.d/basic.conf;
	location /authelia { include custom.d/reverse_proxy/authelia.conf; }
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/authelia_request.conf;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}

server {
    listen 80;
    server_name zb.zerolabs.sh;
    return 301 https://zb.zerolabs.sh$request_uri;
}
