server {
	listen 10051;
	server_name zb.zerolabs.sh zb.cleberg.net;

	if ($host = zb.cleberg.net) {
	    return 301 https://zb.zerolabs.sh$request_uri;
	}
	include custom.d/basic.conf;
	location /authelia { include custom.d/reverse_proxy/authelia.conf; }
	location / {
		proxy_pass $backend_address;
		include custom.d/reverse_proxy/authelia_request.conf;
		include custom.d/reverse_proxy/basic.conf;
	}
	include custom.d/security/robots_index_only.conf;
}

