server {
        listen 10000;
        server_name www.zerolabs.sh;
        return 301 $scheme://zerolabs.sh$request_uri;
}

server {
        listen 10000;
        server_name zerolabs.sh;
        root /var/www/zerolabs.sh/;
        include custom.d/basic.conf;
        location / { try_files $uri $uri/ =404; }
}
